import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#000000',
  '--slot4-page-text': '#c8c2b6',
  '--slot4-panel-bg': '#0a0a0a',
  '--slot4-surface-bg': '#0a0a0a',
  '--slot4-muted-text': '#7a7468',
  '--slot4-soft-muted-text': '#5a5448',
  '--slot4-accent': '#c9a96e',
  '--slot4-accent-fill': '#c9a96e',
  '--slot4-accent-soft': 'rgba(201,169,110,0.1)',
  '--slot4-on-accent': '#000000',
  '--slot4-dark-bg': '#0a0a0a',
  '--slot4-dark-text': '#e8e2d6',
  '--slot4-media-bg': '#111111',
  '--slot4-cream': '#0d0d0d',
  '--slot4-warm': '#0a0a0a',
  '--slot4-lavender': '#080808',
  '--slot4-gray': '#0d0d0d',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#000000',
  '--editable-page-text': '#c8c2b6',
  '--editable-container': '1200px',
  '--editable-border': 'rgba(255,255,255,0.08)',
  '--editable-nav-bg': 'transparent',
  '--editable-nav-text': '#c8c2b6',
  '--editable-nav-active': '#c9a96e',
  '--editable-nav-active-text': '#000000',
  '--editable-cta-bg': '#c9a96e',
  '--editable-cta-text': '#000000',
  '--editable-search-bg': '#0a0a0a',
  '--editable-footer-bg': '#000000',
  '--editable-footer-text': '#c8c2b6',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-black',
  pageText: 'text-[#c8c2b6]',
  panelBg: 'bg-[#0a0a0a]',
  panelText: 'text-[#c8c2b6]',
  surfaceBg: 'bg-[#0a0a0a]',
  surfaceText: 'text-[#c8c2b6]',
  mutedText: 'text-[#7a7468]',
  softMutedText: 'text-[#5a5448]',
  accentText: 'text-[#c9a96e]',
  accentBg: 'bg-[#c9a96e]',
  accentSoftBg: 'bg-[rgba(201,169,110,0.1)]',
  accentSoftText: 'text-[#c9a96e]',
  onAccentText: 'text-black',
  darkBg: 'bg-[#0a0a0a]',
  darkText: 'text-[#e8e2d6]',
  mediaBg: 'bg-[#111111]',
  creamBg: 'bg-[#0d0d0d]',
  warmBg: 'bg-[#0a0a0a]',
  lavenderBg: 'bg-[#080808]',
  grayBg: 'bg-[#0d0d0d]',
  border: 'border-white/[0.08]',
  darkBorder: 'border-white/[0.06]',
  shadow: 'shadow-none',
  shadowStrong: 'shadow-[0_20px_60px_rgba(0,0,0,0.6)]',
  overlay: 'bg-[linear-gradient(180deg,transparent,rgba(0,0,0,0.85))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen bg-black text-[#c8c2b6]`,
    section: 'mx-auto w-full max-w-[1200px] px-6 sm:px-8 lg:px-10',
    sectionY: 'py-20 sm:py-24 lg:py-32',
  },
  layout: {
    safeGrid: 'grid gap-8 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-16 lg:grid-cols-2 lg:items-start',
    rail: 'flex snap-x gap-6 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[200px] shrink-0 snap-start sm:w-[240px]',
  },
  type: {
    eyebrow: 'text-[11px] font-medium uppercase tracking-[0.35em] text-[#7a7468]',
    heroTitle: 'font-[var(--editable-font-display)] text-4xl font-light leading-[1.1] tracking-[0.12em] uppercase text-[#e8e2d6] sm:text-5xl lg:text-7xl',
    sectionTitle: 'font-[var(--editable-font-display)] text-3xl font-light tracking-[0.12em] uppercase text-[#e8e2d6] sm:text-4xl',
    body: 'text-base leading-[1.9] text-[#c8c2b6]',
  },
  surface: {
    card: `border-b border-white/[0.06] bg-transparent`,
    soft: `border border-white/[0.06] bg-[#0a0a0a]`,
    dark: `bg-[#0a0a0a] border border-white/[0.06]`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 border border-[#c9a96e] bg-transparent px-8 py-3 text-[11px] font-medium uppercase tracking-[0.3em] text-[#c9a96e] transition duration-500 hover:bg-[#c9a96e] hover:text-black`,
    secondary: `inline-flex items-center justify-center gap-2 border border-white/[0.15] bg-transparent px-8 py-3 text-[11px] font-medium uppercase tracking-[0.3em] text-[#c8c2b6] transition duration-500 hover:border-white/40 hover:text-[#e8e2d6]`,
    accent: `inline-flex items-center justify-center gap-2 bg-[#c9a96e] px-8 py-3 text-[11px] font-medium uppercase tracking-[0.3em] text-black transition duration-500 hover:bg-[#d4b87a]`,
  },
  media: {
    frame: `relative overflow-hidden bg-[#111111]`,
    ratio: 'aspect-[3/4]',
  },
  motion: {
    lift: 'transition duration-500 hover:opacity-80',
    fade: 'transition duration-500 hover:opacity-60',
  },
} as const

export const aiLayoutRules = [
  'Dark cinematic palette: pure black bg, warm cream text, gold accents.',
  'Wide letter-spacing on all headings, uppercase throughout.',
  'Floating scattered image cards on homepage.',
  'Track-listing style numbered rows on archive pages.',
  'Minimal bottom navigation: THE WORK / ABOUT / CONTACT.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
